### ISSUE TITLE
meta.licenses rewrite

### ISSUE THREAD

**Issue by codyopel** [triton/triton#86]
### stdenv
- [ ] Rewrite license evaluation to fix incompatible licenses
### lib/licenses.nix
- [ ] Implement redistributable boolean
- [ ] Implement booleans for license compatibility
